# Use node official image as a base
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy all files
COPY . .

# Expose the port
EXPOSE 5000

# Start the app
CMD ["npm", "start"]
